// FIXME: I WILL CREATE AN ORDER SLICE AND ONCE THE USER MAKE AN ORDER, WE WILL UPDATE THIS ORDER STATE AND THEN RENDER THE ORDER LAYOUT (OR I THINK I WILL REDIRECT TO THE ORDER PAGE). I WILL SEE TOMORROW HOW I WILL IMPLEMENT THAT

export function getOrder() {
  // const
}
